"""init project

Revision ID: ef210fceb0a0
Revises: 
Create Date: 2025-08-25 10:04:40.590312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef210fceb0a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('AdminID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('PostCode', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('Province', sa.String(length=100), nullable=True),
    sa.Column('Street', sa.String(length=100), nullable=True),
    sa.Column('NationalID', sa.String(length=20), nullable=True),
    sa.Column('UserRole', sa.Enum('Admin', 'GroupAdmin', name='userroleenum'), nullable=False),
    sa.Column('Password', sa.String(length=128), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('AdminID')
    )
    op.create_index(op.f('ix_admin_AdminID'), 'admin', ['AdminID'], unique=False)
    op.create_table('message',
    sa.Column('MessageID', sa.Integer(), nullable=False),
    sa.Column('MessageText', sa.Text(), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('GivenToWhome', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['admin.AdminID'], ),
    sa.ForeignKeyConstraint(['GivenToWhome'], ['register.RegisterID'], ),
    sa.PrimaryKeyConstraint('MessageID')
    )
    op.create_index(op.f('ix_message_MessageID'), 'message', ['MessageID'], unique=False)
    op.create_table('register',
    sa.Column('RegisterID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=False),
    sa.Column('LastName', sa.String(), nullable=False),
    sa.Column('Phone', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('City', sa.String(), nullable=True),
    sa.Column('Province', sa.String(), nullable=True),
    sa.Column('Street', sa.String(), nullable=True),
    sa.Column('NameFather', sa.String(), nullable=True),
    sa.Column('NationalID', sa.String(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('MessageID', sa.Integer(), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Region', sa.String(), nullable=True),
    sa.Column('Gender', sa.String(), nullable=True),
    sa.Column('HousebandFirstName', sa.String(), nullable=True),
    sa.Column('HousbandLastName', sa.String(), nullable=True),
    sa.Column('ReasonMissingHouseband', sa.String(), nullable=True),
    sa.Column('UnderOrganizationName', sa.String(), nullable=True),
    sa.Column('EducationLevel', sa.String(), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('IncomeForm', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy'], ['admin.AdminID'], ),
    sa.ForeignKeyConstraint(['MessageID'], ['message.MessageID'], ),
    sa.PrimaryKeyConstraint('RegisterID')
    )
    op.create_index(op.f('ix_register_RegisterID'), 'register', ['RegisterID'], unique=False)
    op.create_table('children_of_registre',
    sa.Column('ChildrenOfRegistreID', sa.Integer(), nullable=False),
    sa.Column('RegisterID', sa.Integer(), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Gender', sa.String(), nullable=True),
    sa.Column('NationalID', sa.String(), nullable=True),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('LastName', sa.String(), nullable=True),
    sa.Column('EducationLevel', sa.String(), nullable=True),
    sa.Column('CreatedDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('UpdatedDate', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['RegisterID'], ['register.RegisterID'], ),
    sa.PrimaryKeyConstraint('ChildrenOfRegistreID')
    )
    op.create_index(op.f('ix_children_of_registre_ChildrenOfRegistreID'), 'children_of_registre', ['ChildrenOfRegistreID'], unique=False)
    op.create_table('good',
    sa.Column('GoodID', sa.Integer(), nullable=False),
    sa.Column('TypeGood', sa.String(), nullable=False),
    sa.Column('NumberGood', sa.Integer(), nullable=False),
    sa.Column('GiventoWhome', sa.Integer(), nullable=False),
    sa.Column('GivenBy', sa.Integer(), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('UpdatedDate', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['GivenBy'], ['admin.AdminID'], ),
    sa.ForeignKeyConstraint(['GiventoWhome'], ['register.RegisterID'], ),
    sa.PrimaryKeyConstraint('GoodID')
    )
    op.create_index(op.f('ix_good_GoodID'), 'good', ['GoodID'], unique=False)
    op.create_index(op.f('ix_good_TypeGood'), 'good', ['TypeGood'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_good_TypeGood'), table_name='good')
    op.drop_index(op.f('ix_good_GoodID'), table_name='good')
    op.drop_table('good')
    op.drop_index(op.f('ix_children_of_registre_ChildrenOfRegistreID'), table_name='children_of_registre')
    op.drop_table('children_of_registre')
    op.drop_index(op.f('ix_register_RegisterID'), table_name='register')
    op.drop_table('register')
    op.drop_index(op.f('ix_message_MessageID'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_admin_AdminID'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
