"""add lat and long

Revision ID: 973a8986aa0a
Revises: 610bf5852bec
Create Date: 2025-08-31 19:42:05.413098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973a8986aa0a'
down_revision = '610bf5852bec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('Latitude', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('Longitude', sa.Text(), nullable=True))
    op.add_column('register', sa.Column('Latitude', sa.Text(), nullable=True))
    op.add_column('register', sa.Column('Longitude', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'Longitude')
    op.drop_column('register', 'Latitude')
    op.drop_column('admin', 'Longitude')
    op.drop_column('admin', 'Latitude')
    # ### end Alembic commands ###
